### ISSUE TITLE
[rmz] Symbolic Links

### ISSUE THREAD

**Issue by Elvyria** [SUPERCILEX/fuc#11]
I'm getting a pretty destructive behavior, while trying to remove symbolic link. 
`rmz` fails to remove symbolic link and responds with `Not a directory (os error 20)`, in reality, it nukes contents of the directory, that symbolic link points to.

I know that `rmz` is not advertised to be able to remove symbolic links (no idea if they fall under `file` category), but removing content that lies under it - is a very different story. Not sure if it's a bug or a feature request, but it would be better if this behavior would be ether documented or fixed.

Version: `1.1.1`

**Comment by SUPERCILEX** [comment]
Shit, I'm really sorry about that, definitely a bug. I goofed using `metadata` instead of `symlink_metadata`. Added some regression tests and released v1.1.2.
