### ISSUE TITLE
Add -i / --interactive flags

### ISSUE THREAD

**Issue by jtrv** [SUPERCILEX/fuc#24]
The `-i` / `--interactive` flags can be useful for preventing user errors. I use an abbreviation in fish so that `rm` and `cp` expand to `rm -i` and `cp -i`. So that I must first delete the flag in order to run a potentially dangerous operation.

**Comment by SUPERCILEX** [comment]
Seems pretty reasonable. I think the way it would be implemented in this project is by showing you everything that is about to be deleted in one go instead of asking you successive questions. Otherwise you lose out on cross directory parallel deletions.

**Comment by SUPERCILEX** [comment]
I'm not going to have the time to implement this (but I'm still open to somebody else sending a PR), so closing.

I'd recommend first using `echo` to check the files that will be operated on. Filed this for nushell: https://github.com/nushell/nushell/issues/11139
