### ISSUE TITLE
How do I learn about knowledge behind this project?

### ISSUE THREAD

**Issue by luceat-lux-vestra** [SUPERCILEX/fuc#27]
I want to learn about things need to know to implement like this project on windows.

Please give me some hint.

Thanks.

**Comment by SUPERCILEX** [comment]
You'd need to see if Windows has syscalls which let you accelerate file copies by doing them in kernel.

**Comment by luceat-lux-vestra** [comment]
https://redops.at/en/blog/direct-syscalls-a-journey-from-high-to-low

I'm searching some information about it, articles on the web about direct syscalls explains about security things.

But I guess file operation handler using direct syscalls can have performance benefits because bypasses some function call steps.

(I don't know about things I need to know yet...)
What I want to know is...

Another ways to improve performance.

I'll keep finding this myself but I hope to hear your advice.

Thanks.

**Comment by luceat-lux-vestra** [comment]
https://github.com/apankrat/byenow

I tried but gave up.
`byenow` seems implements what you said but it's cpp.
