### ISSUE TITLE
How to make benchmarks run fine on windows?

### ISSUE THREAD

**Issue by luceat-lux-vestra** [SUPERCILEX/fuc#29]
I want to benchmark for some of windows default commands like `rd`, `robocopy`.

but I can't make it work because of error.

>Benchmark 1: rmdir /S /Q D:/tmp/
Error: The preparation command terminated with a non-zero exit code. Append ' || true' to the command if you are sure that this can be ignored.

It works well with release files of this project, without rmdir lines in batch script.

Please help.

Not working code here.(windows batch script)
````
@echo off
for %%G in (0,1G) do (
 for %%F in (10,10_000,100_000,1M) do (
    hyperfine --warmup 3 -N ^
      --export-markdown "benches/remove_%%F_files_%%G_bytes.md" ^
      --export-json "benches/remove_%%F_files_%%G_bytes.json" ^
      --prepare "ftzz g -n %%F -b %%G "D:/tmp/ftzz"" ^
        "rmdir /S /Q "D:/tmp/"" ^
        "./target/release/rm_stdlib "D:/tmp/ftzz"" ^
        "./target/release/rm_rayon "D:/tmp/ftzz"" ^
        "./target/release/rm_remove_dir_all "D:/tmp/ftzz"" ^
        "./target/release/rmz "D:/tmp/ftzz""
    )

  hyperfine --warmup 3 -N ^
    --export-markdown "benches/remove_100_000_files_%%G_bytes_0_depth.md" ^
    --export-json "benches/remove_100_000_files_%%G_bytes_0_depth.json" ^
    --prepare "ftzz g -n 100_000 -b %%G -d 0 "D:/tmp/ftzz"" ^
      "rmdir /S /Q "D:/tmp/"" ^
      "./target/release/rm_stdlib "D:/tmp/ftzz"" ^
      "./target/release/rm_rayon "D:/tmp/ftzz"" ^
      "./target/release/rm_remove_dir_all "D:/tmp/ftzz"" ^
      "./target/release/rmz "D:/tmp/ftzz""

  hyperfine --warmup 3 -N ^
    --export-markdown "benches/remove_100_000_files_%%G_bytes_5_files_per_dir.md" ^
    --export-json "benches/remove_100_000_files_%%G_bytes_5_files_per_dir.json" ^
    --prepare "ftzz g -n 100_000 -b %%G -r 5 "D:/tmp/ftzz"" ^
      "rmdir /S /Q "D:/tmp/"" ^
      "./target/release/rm_stdlib "D:/tmp/ftzz"" ^
      "./target/release/rm_rayon "D:/tmp/ftzz"" ^
      "./target/release/rm_remove_dir_all "D:/tmp/ftzz"" ^
      "./target/release/rmz "D:/tmp/ftzz""
)
```

**Comment by luceat-lux-vestra** [comment]
rm_rayon is the fastest one except for first bench(empty files) on windows 11(tested on HDD).

**Comment by SUPERCILEX** [comment]
As expected for windows right now since we're just forwarding to https://github.com/XAMPPRocky/remove_dir_all/blob/master/Cargo.toml. In that note, I noticed that the parallel feature is disabled by default. If you enable it here (https://github.com/SUPERCILEX/fuc/blob/cb34600eeb590fbb3f30f88ee447154ee356c744/fuc_engine/Cargo.toml#L24), you should get about the same performance.

Can you try that and share benchmarks?

**Comment by luceat-lux-vestra** [comment]
@SUPERCILEX not relevant, do you know some windows internals?

I hope to enhance windows default file operation by minifilter driver because copyhook implementation seems have some limitations. 

But I don't know about minifilter and windows internals and many other fast handlers out there are using copyhook.

I hope to get some advice on this.

Thanks.

**Comment by luceat-lux-vestra** [comment]
[benches.zip](https://github.com/SUPERCILEX/fuc/files/13625611/benches.zip)

I can't wait to finish remove benchmark running on HDD.
But I guess almost last phase.

need to adjust values or run benches on SSD...
HDD takes too much time.

**Comment by SUPERCILEX** [comment]
Thanks! So that's with the `parallel` feature enabled? Seems like a win for the large benchmarks.

**Comment by luceat-lux-vestra** [comment]
Yes, I enabled parallel feature.

**Comment by SUPERCILEX** [comment]
Sweet! I just pushed https://github.com/SUPERCILEX/fuc/commit/844b20b9c94154f34ebe60b6166355bb8f2a52df

**Comment by luceat-lux-vestra** [comment]
[benches (2).zip](https://github.com/SUPERCILEX/fuc/files/13626916/benches.2.zip)

Added copy benchmarks, just `stdlib`, `rayon`, `cpz`.
I'll try this with `robocopy` later.
