### ISSUE TITLE
add option to rename top directory before recursive delete

### ISSUE THREAD

**Issue by andreasstieger** [SUPERCILEX/fuc#33]
Let's assume that a somewhat frequent usage of `rmz` is to recursively delete a tree and putting another tree in it's place. During the recursive operation, however fast, the original directory entry name remains blocked for use. The perceived speed of `rmz` could be improved by adding an option (`--rename-before-deletion`) to rename the target directory to a non-conflicting, temporary name (`.rmz-deletion-$PID-$XXXX`). For a single interactive shell this only makes sense when rmz is run in the background.

**Comment by SUPERCILEX** [comment]
This sounds useful, but I can't decide if it's a good idea to put in rmz itself. My question is why not simply type out the `mv` command yourself? And if it were implemented in rmz, why not always do the move?

**Comment by andreasstieger** [comment]
I think it's usability sugar, not the core goal of the project. Couple of lines in shell script to wrap for repeated use, so no a big deal. Thanks for considering.
