### ISSUE TITLE
Add a progressbar or copy-paste speed

### ISSUE THREAD

**Issue by krakotay** [SUPERCILEX/fuc#38]
When I measure, i can see a fantastic improve of speed, but it will be much more beautiful, if user can see speed of copying
![image](https://github.com/user-attachments/assets/76ed73d4-c78a-4097-b86a-f08995c714a5)

**Comment by SUPERCILEX** [comment]
This was discussed in https://github.com/SUPERCILEX/fuc/issues/14 and is now documented: https://github.com/SUPERCILEX/fuc/commit/95a2678b991e65b6d916c69131b3e80267a3f88c

**Comment by krakotay** [comment]
> This was discussed in #14 and is now documented: [95a2678](https://github.com/SUPERCILEX/fuc/commit/95a2678b991e65b6d916c69131b3e80267a3f88c)

![image](https://github.com/user-attachments/assets/9ef8cdd1-f8ce-47c4-87a4-f8eb71c1d1ce)
that's strange. I can't see --progress with cpz -h, and cpz --progress makes an Error. When I use just cpz from to, there aren't any difference between vanilla cpz and cpz with progress feature

**Comment by SUPERCILEX** [comment]
Nope, you need to install the binary again but with the progress feature. It's not a flag in the binary itself.

**Comment by SUPERCILEX** [comment]
Oh, just saw you tried re-install. Use `--force` as it suggests.

**Comment by krakotay** [comment]
> Oh, just saw you tried reinstalling. Use `--force` as it suggests.

![image](https://github.com/user-attachments/assets/06a3241a-3b3f-469b-8fa9-722b5e30f7c1)
And... nothing changes. All works excluding progress bar

**Comment by SUPERCILEX** [comment]
There's no progress flag. Now the binary will always show progress.

**Comment by krakotay** [comment]
> There's no progress flag. Now the binary will always show progress.

But there aren't, even with large number of files. For example, in my screenshot I successfully copy windows folder to another folder. I works perfect and fantastic speed, but without progress bar 
![image](https://github.com/user-attachments/assets/4d2e3bc5-6eb4-4e39-a180-f9466364286e)

**Comment by SUPERCILEX** [comment]
Hmmm, how long does the copying take? If less than a second, you probably won't see the progress, but it should definitely be visible with longer copies. Though it's also possible that this is just broken on Windows? I'm not sure.

**Comment by krakotay** [comment]
> Hmmm, how long does the copying take? If less than a second, you probably won't see the progress, but it should definitely be visible with longer copies. Though it's also possible that this is just broken on Windows? I'm not sure.

3 or 4 seconds. Btw, default windows cp used more than 600 seconds xD

**Comment by krakotay** [comment]
> Hmmm, how long does the copying take? If less than a second, you probably won't see the progress, but it should definitely be visible with longer copies. Though it's also possible that this is just broken on Windows? I'm not sure.

I tried with measurements, cpz copying takes 19 sec (compare to 656 with default cp)

**Comment by SUPERCILEX** [comment]
Ohhhh, hold on I'm stupid there's no logging on non-Linux builds.

**Comment by krakotay** [comment]
> Ohhhh, hold on I'm stupid there's no logging on non-Linux builds.

well, in Linux all works. It's unusual progress info btw =) Without copy speed or progress-bar 
![image](https://github.com/user-attachments/assets/08c58490-b7d8-4247-b314-12d03f15ea95), just something like this one

**Comment by SUPERCILEX** [comment]
Ok, can you try `cargo install cpz --features progress --force --git https://github.com/SUPERCILEX/fuc`

**Comment by krakotay** [comment]
> Ok, can you try `cargo install cpz --features progress --force --git https://github.com/SUPERCILEX/fuc`

```powershell
Compiling fuc_engine v1.1.6 (C:\Users\krakotay\.cargo\git\checkouts\fuc-a8eff962d757a116\02d0910\fuc_engine)
error[E0425]: cannot find value `follow_symlinks` in this scope
   --> fuc_engine\src\ops\copy.rs:649:22
    |
649 |         #[cfg(unix)] follow_symlinks: bool,
    |                      ^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find value `root_to_inode` in this scope
   --> fuc_engine\src\ops\copy.rs:650:22
    |
650 |         #[cfg(unix)] root_to_inode: Option<u64>,
    |                      ^^^^^^^^^^^^^ not found in this scope

error[E0554]: `#![feature]` may not be used on the stable release channel
 --> fuc_engine\src\lib.rs:1:12
  |
1 | #![feature(lazy_cell_into_inner)]
  |            ^^^^^^^^^^^^^^^^^^^^

error[E0635]: unknown feature `lazy_cell_into_inner`
 --> fuc_engine\src\lib.rs:1:12
  |
1 | #![feature(lazy_cell_into_inner)]
  |            ^^^^^^^^^^^^^^^^^^^^

Some errors have detailed explanations: E0425, E0554, E0635.
For more information about an error, try `rustc --explain E0425`.
error: could not compile `fuc_engine` (lib) due to 4 previous errors
warning: build failed, waiting for other jobs to finish...
error: failed to compile `cpz v1.1.6 (https://github.com/SUPERCILEX/fuc#02d0910c)`, intermediate artifacts can be found at `C:\Users\krakotay\AppData\Local\Temp\cargo-installNGTSZh`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.```

Well, something like this one. And in the beginning `Installing cpz v1.1.6 (https://github.com/SUPERCILEX/fuc#02d0910c)`, why is 1.1.6?

**Comment by krakotay** [comment]
> Ok, can you try `cargo install cpz --features progress --force --git https://github.com/SUPERCILEX/fuc`

![image](https://github.com/user-attachments/assets/1c4e9451-1896-45ea-ab29-139204be22a4)
well, even i tried to build locally, i have this one. just with -F progress

**Comment by SUPERCILEX** [comment]
Well this is icky, I guess the tracing attribute doesn't support cfg-ed args. Can you try installing again? Should be fixed.

**Comment by krakotay** [comment]
![image](https://github.com/user-attachments/assets/d5e3766c-8ce3-495d-9f65-e174f39d4449)
nothing changed

**Comment by SUPERCILEX** [comment]
Oh for that you just need to do `cargo +nightly ...` and `rustup install nightly` if you don't have it.

**Comment by krakotay** [comment]
> Oh for that you just need to do `cargo +nightly ...` and `rustup install nightly` if you don't have it.

it's already nightly 

```powershell
PS C:\Users\krakotay\Documents\fuc\cpz> rustc --version
rustc 1.81.0-nightly (fcaa6fdfb 2024-07-13)
PS C:\Users\krakotay\Documents\fuc\cpz> cargo build --release --features progress
   Compiling tracing-indicatif v0.3.6
   Compiling fuc_engine v1.1.6 (C:\Users\krakotay\Documents\fuc\fuc_engine)
   Compiling clap v4.5.9
error[E0425]: cannot find value `follow_symlinks` in this scope
   --> fuc_engine\src\ops\copy.rs:649:22
    |
649 |         #[cfg(unix)] follow_symlinks: bool,
    |                      ^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find value `root_to_inode` in this scope
   --> fuc_engine\src\ops\copy.rs:650:22
    |
650 |         #[cfg(unix)] root_to_inode: Option<u64>,
    |                      ^^^^^^^^^^^^^ not found in this scope

For more information about this error, try `rustc --explain E0425`.
error: could not compile `fuc_engine` (lib) due to 2 previous errors
warning: build failed, waiting for other jobs to finish...
PS C:\Users\krakotay\Documents\fuc\cpz> cargo --version
cargo 1.81.0-nightly (154fdac39 2024-07-07)
PS C:\Users\krakotay\Documents\fuc\cpz>
```

**Comment by krakotay** [comment]
Thank you, all works!

**Comment by krakotay** [comment]
> Yay!
btw, progress bar in rmz doesn't work... 
![image](https://github.com/user-attachments/assets/3309ffd8-cb20-4dec-8f72-f706dcba1877)

**Comment by SUPERCILEX** [comment]
Yeah, Windows progress support isn't going to be implemented because we use https://github.com/XAMPPRocky/remove_dir_all. Honestly not sure what that lib does extra so maybe I could just use rmz's non-linux implantation on Windows? Don't know.

**Comment by SUPERCILEX** [comment]
It reduces performance, so I have it compiled out entirely by default. At some point I've thought about including a dumb counter that indicates the number of files that have been copied as a less costly way to indicate progress. But it'd still slow things down so I didn't build it.
